### ISSUE TITLE
Can not sync latest block on testnet

### ISSUE THREAD

**Issue by jualy007** [tronprotocol/tron-deployment#24]
Start command:
sudo bash deploy_tron.sh --app FullNode --net testnet --heap-size 13108m

I found errors in tron.log:
17:30:46.768 INFO  [pool-6-thread-1] [o.t.c.d.Manager](Manager.java:1577) PreValidate Transaction Sign, size:1,block num:302
17:30:46.776 INFO  [pool-6-thread-1] [o.t.c.w.WitnessController](WitnessController.java:222) scheduledWitness:41c0e86ce4f5c476301af6b2aeed049e918e6ad4c7, currentSlot:515677898
17:30:46.792 ERROR [pool-6-thread-1] [o.t.c.d.Manager](Manager.java:877) Bad chain parameter id
org.tron.core.exception.ContractValidateException: Bad chain parameter id
        at org.tron.core.actuator.ProposalCreateActuator.validateValue(ProposalCreateActuator.java:211)
        at org.tron.core.actuator.ProposalCreateActuator.validate(ProposalCreateActuator.java:136)
        at org.tron.common.runtime.RuntimeImpl.precompiled(RuntimeImpl.java:162)
        at org.tron.common.runtime.RuntimeImpl.execute(RuntimeImpl.java:171)
        at org.tron.core.db.TransactionTrace.exec(TransactionTrace.java:131)
        at org.tron.core.db.Manager.processTransaction(Manager.java:1037)
        at org.tron.core.db.Manager.processBlock(Manager.java:1271)
        at org.tron.core.db.Manager.applyBlock(Manager.java:678)
        at org.tron.core.db.Manager.pushBlock(Manager.java:874)
        at org.tron.core.net.node.NodeDelegateImpl.handleBlock(NodeDelegateImpl.java:71)
        at org.tron.core.net.node.NodeImpl.processSyncBlock(NodeImpl.java:792)
        at org.tron.core.net.node.NodeImpl.lambda$handleSyncBlock$27(NodeImpl.java:575)
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
        at org.tron.core.net.node.NodeImpl.handleSyncBlock(NodeImpl.java:550)
        at org.tron.core.net.node.NodeImpl.lambda$activeTronPump$9(NodeImpl.java:407)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
17:30:46.794 ERROR [pool-6-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:800) We get a bad block Num:302,ID:000000000000012eeb10598e36dd35066040e3881af6481e372755f597cbaa02, reason is ContractValidate exception,Bad chain parameter id

can anyone check the problem? Need update p2p version?

**Comment by BSGILL012** [comment]
P2P

**Comment by shydesky** [comment]
may be your database is broken. we recommand that delete your database and use the db.version = 2 in the config.conf
