### ISSUE TITLE
Start tron error in ubuntu 16.04

### ISSUE THREAD

**Issue by bingfeng28** [tronprotocol/tron-deployment#3]
Hi,
I followed TronDeployment for building tron on ubuntu 16.04
I got this error when tron is starting. 

18:08:56.826 INFO  [main] [o.t.p.FullNode](FullNode.java:22) Full node running.
18:08:57.198 INFO  [main] [o.t.c.c.a.Args](Args.java:637) Bind address wasn't set, Punching to identify it...
18:08:58.064 INFO  [main] [o.t.c.c.a.Args](Args.java:640) UDP local bound to: 10.142.0.12
18:08:58.067 INFO  [main] [o.t.c.c.a.Args](Args.java:655) External IP wasn't set, using checkip.amazonaws.com to identify it...
18:08:58.135 INFO  [main] [o.t.c.c.a.Args](Args.java:669) External address identified: 35.231.48.233
18:08:58.135 INFO  [main] [o.t.c.c.a.Args](Args.java:710) 

18:08:58.135 INFO  [main] [o.t.c.c.a.Args](Args.java:711) ************************ Net config ************************
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:712) P2P version: 11111
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:713) Bind IP: 10.142.0.12
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:714) External IP: 35.231.48.233
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:715) Listen port: 18888
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:716) Discover enable: true
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:717) Active node size: 0
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:718) Passive node size: 0
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:719) Seed node size: 29
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:720) Max connection: 30
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:721) Max connection with same IP: 2
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:722) ************************ Backup config ************************
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:723) Backup listen port: 10001
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:724) Backup member size: 0
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:725) Backup priority: 8
18:08:58.136 INFO  [main] [o.t.c.c.a.Args](Args.java:726) 

18:08:58.345 INFO  [main] [o.s.c.a.AnnotationConfigApplicationContext](AbstractApplicationContext.java:573) Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@103f852: startup date [Wed Jul 25 18:08:58 UTC 2018]; root of context hierarchy
18:08:59.899 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
18:09:00.329 WARN  [main] [o.s.c.a.AnnotationConfigApplicationContext](AbstractApplicationContext.java:544) Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.node.NodeImpl org.tron.common.application.ApplicationImpl.p2pNode; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeImpl' defined in URL [jar:file:/home/bing/FullNode/FullNode.jar!/org/tron/core/net/node/NodeImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.net.node.NodeImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.tron.program.FullNode.main(FullNode.java:35)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.node.NodeImpl org.tron.common.application.ApplicationImpl.p2pNode; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeImpl' defined in URL [jar:file:/home/bing/FullNode/FullNode.jar!/org/tron/core/net/node/NodeImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.net.node.NodeImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 11 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeImpl' defined in URL [jar:file:/home/bing/FullNode/FullNode.jar!/org/tron/core/net/node/NodeImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.net.node.NodeImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1105)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
	... 13 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.net.node.NodeImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	... 24 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237)
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:151)
	at org.tron.core.net.node.NodeImpl.<init>(NodeImpl.java:204)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 26 common frames omitted
18:09:00.342 ERROR [main] [general](DefaultConfig.java:26) Uncaught exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.node.NodeImpl org.tron.common.application.ApplicationImpl.p2pNode; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeImpl' defined in URL [jar:file:/home/bing/FullNode/FullNode.jar!/org/tron/core/net/node/NodeImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.net.node.NodeImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.tron.program.FullNode.main(FullNode.java:35)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.node.NodeImpl org.tron.common.application.ApplicationImpl.p2pNode; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeImpl' defined in URL [jar:file:/home/bing/FullNode/FullNode.jar!/org/tron/core/net/node/NodeImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.net.node.NodeImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 11 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nodeImpl' defined in URL [jar:file:/home/bing/FullNode/FullNode.jar!/org/tron/core/net/node/NodeImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.net.node.NodeImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1105)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1145)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1069)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:967)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
	... 13 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.net.node.NodeImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	... 24 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237)
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:151)
	at org.tron.core.net.node.NodeImpl.<init>(NodeImpl.java:204)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 26 common frames omitted

**Comment by tjchern** [comment]
Hi, How much is your cpu core?
